/*
	Autogenerated File (generate_opcodes.py).
*/

#pragma once

#include <stdint.h>
#include "Z80.h"

namespace Z80Instructions
{
	inline uint8_t opcodesCB0x00(Z80& cpu)
	{
		cpu.RLC(cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x01(Z80& cpu)
	{
		cpu.RLC(cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x02(Z80& cpu)
	{
		cpu.RLC(cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x03(Z80& cpu)
	{
		cpu.RLC(cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x04(Z80& cpu)
	{
		cpu.RLC(cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x05(Z80& cpu)
	{
		cpu.RLC(cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x06(Z80& cpu)
	{
		cpu.RLC_HL();
		return 15;
	};

	inline uint8_t opcodesCB0x07(Z80& cpu)
	{
		cpu.RLC(cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x08(Z80& cpu)
	{
		cpu.RRC(cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x09(Z80& cpu)
	{
		cpu.RRC(cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x0a(Z80& cpu)
	{
		cpu.RRC(cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x0b(Z80& cpu)
	{
		cpu.RRC(cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x0c(Z80& cpu)
	{
		cpu.RRC(cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x0d(Z80& cpu)
	{
		cpu.RRC(cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x0e(Z80& cpu)
	{
		cpu.RRC_HL();
		return 15;
	};

	inline uint8_t opcodesCB0x0f(Z80& cpu)
	{
		cpu.RRC(cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x10(Z80& cpu)
	{
		cpu.RL(cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x11(Z80& cpu)
	{
		cpu.RL(cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x12(Z80& cpu)
	{
		cpu.RL(cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x13(Z80& cpu)
	{
		cpu.RL(cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x14(Z80& cpu)
	{
		cpu.RL(cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x15(Z80& cpu)
	{
		cpu.RL(cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x16(Z80& cpu)
	{
		cpu.RL_HL();
		return 15;
	};

	inline uint8_t opcodesCB0x17(Z80& cpu)
	{
		cpu.RL(cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x18(Z80& cpu)
	{
		cpu.RR(cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x19(Z80& cpu)
	{
		cpu.RR(cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x1a(Z80& cpu)
	{
		cpu.RR(cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x1b(Z80& cpu)
	{
		cpu.RR(cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x1c(Z80& cpu)
	{
		cpu.RR(cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x1d(Z80& cpu)
	{
		cpu.RR(cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x1e(Z80& cpu)
	{
		cpu.RR_HL();
		return 15;
	};

	inline uint8_t opcodesCB0x1f(Z80& cpu)
	{
		cpu.RR(cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x20(Z80& cpu)
	{
		cpu.SLA(cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x21(Z80& cpu)
	{
		cpu.SLA(cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x22(Z80& cpu)
	{
		cpu.SLA(cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x23(Z80& cpu)
	{
		cpu.SLA(cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x24(Z80& cpu)
	{
		cpu.SLA(cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x25(Z80& cpu)
	{
		cpu.SLA(cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x26(Z80& cpu)
	{
		cpu.SLA_HL();
		return 15;
	};

	inline uint8_t opcodesCB0x27(Z80& cpu)
	{
		cpu.SLA(cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x28(Z80& cpu)
	{
		cpu.SRA(cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x29(Z80& cpu)
	{
		cpu.SRA(cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x2a(Z80& cpu)
	{
		cpu.SRA(cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x2b(Z80& cpu)
	{
		cpu.SRA(cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x2c(Z80& cpu)
	{
		cpu.SRA(cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x2d(Z80& cpu)
	{
		cpu.SRA(cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x2e(Z80& cpu)
	{
		cpu.SRA_HL();
		return 15;
	};

	inline uint8_t opcodesCB0x2f(Z80& cpu)
	{
		cpu.SRA(cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x38(Z80& cpu)
	{
		cpu.SRL(cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x39(Z80& cpu)
	{
		cpu.SRL(cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x3a(Z80& cpu)
	{
		cpu.SRL(cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x3b(Z80& cpu)
	{
		cpu.SRL(cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x3c(Z80& cpu)
	{
		cpu.SRL(cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x3d(Z80& cpu)
	{
		cpu.SRL(cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x3e(Z80& cpu)
	{
		cpu.SRL_HL();
		return 15;
	};

	inline uint8_t opcodesCB0x3f(Z80& cpu)
	{
		cpu.SRL(cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x40(Z80& cpu)
	{
		cpu.BIT(0, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x41(Z80& cpu)
	{
		cpu.BIT(0, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x42(Z80& cpu)
	{
		cpu.BIT(0, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x43(Z80& cpu)
	{
		cpu.BIT(0, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x44(Z80& cpu)
	{
		cpu.BIT(0, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x45(Z80& cpu)
	{
		cpu.BIT(0, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x46(Z80& cpu)
	{
		cpu.BIT_HL(0);
		return 12;
	};

	inline uint8_t opcodesCB0x47(Z80& cpu)
	{
		cpu.BIT(0, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x48(Z80& cpu)
	{
		cpu.BIT(1, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x49(Z80& cpu)
	{
		cpu.BIT(1, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x4a(Z80& cpu)
	{
		cpu.BIT(1, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x4b(Z80& cpu)
	{
		cpu.BIT(1, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x4c(Z80& cpu)
	{
		cpu.BIT(1, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x4d(Z80& cpu)
	{
		cpu.BIT(1, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x4e(Z80& cpu)
	{
		cpu.BIT_HL(1);
		return 12;
	};

	inline uint8_t opcodesCB0x4f(Z80& cpu)
	{
		cpu.BIT(1, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x50(Z80& cpu)
	{
		cpu.BIT(2, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x51(Z80& cpu)
	{
		cpu.BIT(2, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x52(Z80& cpu)
	{
		cpu.BIT(2, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x53(Z80& cpu)
	{
		cpu.BIT(2, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x54(Z80& cpu)
	{
		cpu.BIT(2, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x55(Z80& cpu)
	{
		cpu.BIT(2, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x56(Z80& cpu)
	{
		cpu.BIT_HL(2);
		return 12;
	};

	inline uint8_t opcodesCB0x57(Z80& cpu)
	{
		cpu.BIT(2, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x58(Z80& cpu)
	{
		cpu.BIT(3, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x59(Z80& cpu)
	{
		cpu.BIT(3, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x5a(Z80& cpu)
	{
		cpu.BIT(3, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x5b(Z80& cpu)
	{
		cpu.BIT(3, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x5c(Z80& cpu)
	{
		cpu.BIT(3, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x5d(Z80& cpu)
	{
		cpu.BIT(3, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x5e(Z80& cpu)
	{
		cpu.BIT_HL(3);
		return 12;
	};

	inline uint8_t opcodesCB0x5f(Z80& cpu)
	{
		cpu.BIT(3, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x60(Z80& cpu)
	{
		cpu.BIT(4, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x61(Z80& cpu)
	{
		cpu.BIT(4, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x62(Z80& cpu)
	{
		cpu.BIT(4, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x63(Z80& cpu)
	{
		cpu.BIT(4, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x64(Z80& cpu)
	{
		cpu.BIT(4, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x65(Z80& cpu)
	{
		cpu.BIT(4, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x66(Z80& cpu)
	{
		cpu.BIT_HL(4);
		return 12;
	};

	inline uint8_t opcodesCB0x67(Z80& cpu)
	{
		cpu.BIT(4, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x68(Z80& cpu)
	{
		cpu.BIT(5, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x69(Z80& cpu)
	{
		cpu.BIT(5, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x6a(Z80& cpu)
	{
		cpu.BIT(5, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x6b(Z80& cpu)
	{
		cpu.BIT(5, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x6c(Z80& cpu)
	{
		cpu.BIT(5, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x6d(Z80& cpu)
	{
		cpu.BIT(5, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x6e(Z80& cpu)
	{
		cpu.BIT_HL(5);
		return 12;
	};

	inline uint8_t opcodesCB0x6f(Z80& cpu)
	{
		cpu.BIT(5, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x70(Z80& cpu)
	{
		cpu.BIT(6, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x71(Z80& cpu)
	{
		cpu.BIT(6, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x72(Z80& cpu)
	{
		cpu.BIT(6, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x73(Z80& cpu)
	{
		cpu.BIT(6, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x74(Z80& cpu)
	{
		cpu.BIT(6, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x75(Z80& cpu)
	{
		cpu.BIT(6, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x76(Z80& cpu)
	{
		cpu.BIT_HL(6);
		return 12;
	};

	inline uint8_t opcodesCB0x77(Z80& cpu)
	{
		cpu.BIT(6, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x78(Z80& cpu)
	{
		cpu.BIT(7, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x79(Z80& cpu)
	{
		cpu.BIT(7, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x7a(Z80& cpu)
	{
		cpu.BIT(7, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x7b(Z80& cpu)
	{
		cpu.BIT(7, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x7c(Z80& cpu)
	{
		cpu.BIT(7, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x7d(Z80& cpu)
	{
		cpu.BIT(7, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x7e(Z80& cpu)
	{
		cpu.BIT_HL(7);
		return 12;
	};

	inline uint8_t opcodesCB0x7f(Z80& cpu)
	{
		cpu.BIT(7, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x80(Z80& cpu)
	{
		cpu.RES(0, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x81(Z80& cpu)
	{
		cpu.RES(0, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x82(Z80& cpu)
	{
		cpu.RES(0, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x83(Z80& cpu)
	{
		cpu.RES(0, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x84(Z80& cpu)
	{
		cpu.RES(0, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x85(Z80& cpu)
	{
		cpu.RES(0, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x86(Z80& cpu)
	{
		cpu.RES_HL(0);
		return 15;
	};

	inline uint8_t opcodesCB0x87(Z80& cpu)
	{
		cpu.RES(0, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x88(Z80& cpu)
	{
		cpu.RES(1, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x89(Z80& cpu)
	{
		cpu.RES(1, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x8a(Z80& cpu)
	{
		cpu.RES(1, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x8b(Z80& cpu)
	{
		cpu.RES(1, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x8c(Z80& cpu)
	{
		cpu.RES(1, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x8d(Z80& cpu)
	{
		cpu.RES(1, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x8e(Z80& cpu)
	{
		cpu.RES_HL(1);
		return 15;
	};

	inline uint8_t opcodesCB0x8f(Z80& cpu)
	{
		cpu.RES(1, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x90(Z80& cpu)
	{
		cpu.RES(2, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x91(Z80& cpu)
	{
		cpu.RES(2, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x92(Z80& cpu)
	{
		cpu.RES(2, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x93(Z80& cpu)
	{
		cpu.RES(2, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x94(Z80& cpu)
	{
		cpu.RES(2, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x95(Z80& cpu)
	{
		cpu.RES(2, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x96(Z80& cpu)
	{
		cpu.RES_HL(2);
		return 15;
	};

	inline uint8_t opcodesCB0x97(Z80& cpu)
	{
		cpu.RES(2, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x98(Z80& cpu)
	{
		cpu.RES(3, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x99(Z80& cpu)
	{
		cpu.RES(3, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x9a(Z80& cpu)
	{
		cpu.RES(3, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x9b(Z80& cpu)
	{
		cpu.RES(3, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x9c(Z80& cpu)
	{
		cpu.RES(3, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x9d(Z80& cpu)
	{
		cpu.RES(3, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x9e(Z80& cpu)
	{
		cpu.RES_HL(3);
		return 15;
	};

	inline uint8_t opcodesCB0x9f(Z80& cpu)
	{
		cpu.RES(3, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xa0(Z80& cpu)
	{
		cpu.RES(4, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xa1(Z80& cpu)
	{
		cpu.RES(4, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xa2(Z80& cpu)
	{
		cpu.RES(4, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xa3(Z80& cpu)
	{
		cpu.RES(4, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xa4(Z80& cpu)
	{
		cpu.RES(4, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xa5(Z80& cpu)
	{
		cpu.RES(4, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xa6(Z80& cpu)
	{
		cpu.RES_HL(4);
		return 15;
	};

	inline uint8_t opcodesCB0xa7(Z80& cpu)
	{
		cpu.RES(4, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xa8(Z80& cpu)
	{
		cpu.RES(5, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xa9(Z80& cpu)
	{
		cpu.RES(5, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xaa(Z80& cpu)
	{
		cpu.RES(5, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xab(Z80& cpu)
	{
		cpu.RES(5, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xac(Z80& cpu)
	{
		cpu.RES(5, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xad(Z80& cpu)
	{
		cpu.RES(5, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xae(Z80& cpu)
	{
		cpu.RES_HL(5);
		return 15;
	};

	inline uint8_t opcodesCB0xaf(Z80& cpu)
	{
		cpu.RES(5, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xb0(Z80& cpu)
	{
		cpu.RES(6, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xb1(Z80& cpu)
	{
		cpu.RES(6, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xb2(Z80& cpu)
	{
		cpu.RES(6, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xb3(Z80& cpu)
	{
		cpu.RES(6, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xb4(Z80& cpu)
	{
		cpu.RES(6, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xb5(Z80& cpu)
	{
		cpu.RES(6, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xb6(Z80& cpu)
	{
		cpu.RES_HL(6);
		return 15;
	};

	inline uint8_t opcodesCB0xb7(Z80& cpu)
	{
		cpu.RES(6, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xb8(Z80& cpu)
	{
		cpu.RES(7, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xb9(Z80& cpu)
	{
		cpu.RES(7, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xba(Z80& cpu)
	{
		cpu.RES(7, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xbb(Z80& cpu)
	{
		cpu.RES(7, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xbc(Z80& cpu)
	{
		cpu.RES(7, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xbd(Z80& cpu)
	{
		cpu.RES(7, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xbe(Z80& cpu)
	{
		cpu.RES_HL(7);
		return 15;
	};

	inline uint8_t opcodesCB0xbf(Z80& cpu)
	{
		cpu.RES(7, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xc0(Z80& cpu)
	{
		cpu.SET(0, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xc1(Z80& cpu)
	{
		cpu.SET(0, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xc2(Z80& cpu)
	{
		cpu.SET(0, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xc3(Z80& cpu)
	{
		cpu.SET(0, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xc4(Z80& cpu)
	{
		cpu.SET(0, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xc5(Z80& cpu)
	{
		cpu.SET(0, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xc6(Z80& cpu)
	{
		cpu.SET_HL(0);
		return 15;
	};

	inline uint8_t opcodesCB0xc7(Z80& cpu)
	{
		cpu.SET(0, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xc8(Z80& cpu)
	{
		cpu.SET(1, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xc9(Z80& cpu)
	{
		cpu.SET(1, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xca(Z80& cpu)
	{
		cpu.SET(1, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xcb(Z80& cpu)
	{
		cpu.SET(1, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xcc(Z80& cpu)
	{
		cpu.SET(1, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xcd(Z80& cpu)
	{
		cpu.SET(1, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xce(Z80& cpu)
	{
		cpu.SET_HL(1);
		return 15;
	};

	inline uint8_t opcodesCB0xcf(Z80& cpu)
	{
		cpu.SET(1, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xd0(Z80& cpu)
	{
		cpu.SET(2, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xd1(Z80& cpu)
	{
		cpu.SET(2, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xd2(Z80& cpu)
	{
		cpu.SET(2, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xd3(Z80& cpu)
	{
		cpu.SET(2, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xd4(Z80& cpu)
	{
		cpu.SET(2, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xd5(Z80& cpu)
	{
		cpu.SET(2, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xd6(Z80& cpu)
	{
		cpu.SET_HL(2);
		return 15;
	};

	inline uint8_t opcodesCB0xd7(Z80& cpu)
	{
		cpu.SET(2, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xd8(Z80& cpu)
	{
		cpu.SET(3, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xd9(Z80& cpu)
	{
		cpu.SET(3, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xda(Z80& cpu)
	{
		cpu.SET(3, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xdb(Z80& cpu)
	{
		cpu.SET(3, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xdc(Z80& cpu)
	{
		cpu.SET(3, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xdd(Z80& cpu)
	{
		cpu.SET(3, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xde(Z80& cpu)
	{
		cpu.SET_HL(3);
		return 15;
	};

	inline uint8_t opcodesCB0xdf(Z80& cpu)
	{
		cpu.SET(3, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xe0(Z80& cpu)
	{
		cpu.SET(4, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xe1(Z80& cpu)
	{
		cpu.SET(4, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xe2(Z80& cpu)
	{
		cpu.SET(4, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xe3(Z80& cpu)
	{
		cpu.SET(4, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xe4(Z80& cpu)
	{
		cpu.SET(4, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xe5(Z80& cpu)
	{
		cpu.SET(4, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xe6(Z80& cpu)
	{
		cpu.SET_HL(4);
		return 15;
	};

	inline uint8_t opcodesCB0xe7(Z80& cpu)
	{
		cpu.SET(4, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xe8(Z80& cpu)
	{
		cpu.SET(5, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xe9(Z80& cpu)
	{
		cpu.SET(5, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xea(Z80& cpu)
	{
		cpu.SET(5, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xeb(Z80& cpu)
	{
		cpu.SET(5, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xec(Z80& cpu)
	{
		cpu.SET(5, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xed(Z80& cpu)
	{
		cpu.SET(5, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xee(Z80& cpu)
	{
		cpu.SET_HL(5);
		return 15;
	};

	inline uint8_t opcodesCB0xef(Z80& cpu)
	{
		cpu.SET(5, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xf0(Z80& cpu)
	{
		cpu.SET(6, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xf1(Z80& cpu)
	{
		cpu.SET(6, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xf2(Z80& cpu)
	{
		cpu.SET(6, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xf3(Z80& cpu)
	{
		cpu.SET(6, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xf4(Z80& cpu)
	{
		cpu.SET(6, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xf5(Z80& cpu)
	{
		cpu.SET(6, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xf6(Z80& cpu)
	{
		cpu.SET_HL(6);
		return 15;
	};

	inline uint8_t opcodesCB0xf7(Z80& cpu)
	{
		cpu.SET(6, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xf8(Z80& cpu)
	{
		cpu.SET(7, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xf9(Z80& cpu)
	{
		cpu.SET(7, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xfa(Z80& cpu)
	{
		cpu.SET(7, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xfb(Z80& cpu)
	{
		cpu.SET(7, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xfc(Z80& cpu)
	{
		cpu.SET(7, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xfd(Z80& cpu)
	{
		cpu.SET(7, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xfe(Z80& cpu)
	{
		cpu.SET_HL(7);
		return 15;
	};

	inline uint8_t opcodesCB0xff(Z80& cpu)
	{
		cpu.SET(7, cpu.m_reg_AF.hi);
		return 8;
	};

	OPCodeFunc s_opcode_cb_funcs [256] = 
	{
		&opcodesED0x00,
		&opcodesED0x01,
		&opcodesED0x02,
		&opcodesED0x03,
		&opcodesED0x04,
		&opcodesED0x05,
		&opcodesED0x06,
		&opcodesED0x07,
		&opcodesED0x08,
		&opcodesED0x09,
		&opcodesED0x0a,
		&opcodesED0x0b,
		&opcodesED0x0c,
		&opcodesED0x0d,
		&opcodesED0x0e,
		&opcodesED0x0f,
		&opcodesED0x10,
		&opcodesED0x11,
		&opcodesED0x12,
		&opcodesED0x13,
		&opcodesED0x14,
		&opcodesED0x15,
		&opcodesED0x16,
		&opcodesED0x17,
		&opcodesED0x18,
		&opcodesED0x19,
		&opcodesED0x1a,
		&opcodesED0x1b,
		&opcodesED0x1c,
		&opcodesED0x1d,
		&opcodesED0x1e,
		&opcodesED0x1f,
		&opcodesED0x20,
		&opcodesED0x21,
		&opcodesED0x22,
		&opcodesED0x23,
		&opcodesED0x24,
		&opcodesED0x25,
		&opcodesED0x26,
		&opcodesED0x27,
		&opcodesED0x28,
		&opcodesED0x29,
		&opcodesED0x2a,
		&opcodesED0x2b,
		&opcodesED0x2c,
		&opcodesED0x2d,
		&opcodesED0x2e,
		&opcodesED0x2f,
		&UnexpectedOPCode
		&UnexpectedOPCode
		&UnexpectedOPCode
		&UnexpectedOPCode
		&UnexpectedOPCode
		&UnexpectedOPCode
		&UnexpectedOPCode
		&UnexpectedOPCode
		&opcodesED0x38,
		&opcodesED0x39,
		&opcodesED0x3a,
		&opcodesED0x3b,
		&opcodesED0x3c,
		&opcodesED0x3d,
		&opcodesED0x3e,
		&opcodesED0x3f,
		&opcodesED0x40,
		&opcodesED0x41,
		&opcodesED0x42,
		&opcodesED0x43,
		&opcodesED0x44,
		&opcodesED0x45,
		&opcodesED0x46,
		&opcodesED0x47,
		&opcodesED0x48,
		&opcodesED0x49,
		&opcodesED0x4a,
		&opcodesED0x4b,
		&opcodesED0x4c,
		&opcodesED0x4d,
		&opcodesED0x4e,
		&opcodesED0x4f,
		&opcodesED0x50,
		&opcodesED0x51,
		&opcodesED0x52,
		&opcodesED0x53,
		&opcodesED0x54,
		&opcodesED0x55,
		&opcodesED0x56,
		&opcodesED0x57,
		&opcodesED0x58,
		&opcodesED0x59,
		&opcodesED0x5a,
		&opcodesED0x5b,
		&opcodesED0x5c,
		&opcodesED0x5d,
		&opcodesED0x5e,
		&opcodesED0x5f,
		&opcodesED0x60,
		&opcodesED0x61,
		&opcodesED0x62,
		&opcodesED0x63,
		&opcodesED0x64,
		&opcodesED0x65,
		&opcodesED0x66,
		&opcodesED0x67,
		&opcodesED0x68,
		&opcodesED0x69,
		&opcodesED0x6a,
		&opcodesED0x6b,
		&opcodesED0x6c,
		&opcodesED0x6d,
		&opcodesED0x6e,
		&opcodesED0x6f,
		&opcodesED0x70,
		&opcodesED0x71,
		&opcodesED0x72,
		&opcodesED0x73,
		&opcodesED0x74,
		&opcodesED0x75,
		&opcodesED0x76,
		&opcodesED0x77,
		&opcodesED0x78,
		&opcodesED0x79,
		&opcodesED0x7a,
		&opcodesED0x7b,
		&opcodesED0x7c,
		&opcodesED0x7d,
		&opcodesED0x7e,
		&opcodesED0x7f,
		&opcodesED0x80,
		&opcodesED0x81,
		&opcodesED0x82,
		&opcodesED0x83,
		&opcodesED0x84,
		&opcodesED0x85,
		&opcodesED0x86,
		&opcodesED0x87,
		&opcodesED0x88,
		&opcodesED0x89,
		&opcodesED0x8a,
		&opcodesED0x8b,
		&opcodesED0x8c,
		&opcodesED0x8d,
		&opcodesED0x8e,
		&opcodesED0x8f,
		&opcodesED0x90,
		&opcodesED0x91,
		&opcodesED0x92,
		&opcodesED0x93,
		&opcodesED0x94,
		&opcodesED0x95,
		&opcodesED0x96,
		&opcodesED0x97,
		&opcodesED0x98,
		&opcodesED0x99,
		&opcodesED0x9a,
		&opcodesED0x9b,
		&opcodesED0x9c,
		&opcodesED0x9d,
		&opcodesED0x9e,
		&opcodesED0x9f,
		&opcodesED0xa0,
		&opcodesED0xa1,
		&opcodesED0xa2,
		&opcodesED0xa3,
		&opcodesED0xa4,
		&opcodesED0xa5,
		&opcodesED0xa6,
		&opcodesED0xa7,
		&opcodesED0xa8,
		&opcodesED0xa9,
		&opcodesED0xaa,
		&opcodesED0xab,
		&opcodesED0xac,
		&opcodesED0xad,
		&opcodesED0xae,
		&opcodesED0xaf,
		&opcodesED0xb0,
		&opcodesED0xb1,
		&opcodesED0xb2,
		&opcodesED0xb3,
		&opcodesED0xb4,
		&opcodesED0xb5,
		&opcodesED0xb6,
		&opcodesED0xb7,
		&opcodesED0xb8,
		&opcodesED0xb9,
		&opcodesED0xba,
		&opcodesED0xbb,
		&opcodesED0xbc,
		&opcodesED0xbd,
		&opcodesED0xbe,
		&opcodesED0xbf,
		&opcodesED0xc0,
		&opcodesED0xc1,
		&opcodesED0xc2,
		&opcodesED0xc3,
		&opcodesED0xc4,
		&opcodesED0xc5,
		&opcodesED0xc6,
		&opcodesED0xc7,
		&opcodesED0xc8,
		&opcodesED0xc9,
		&opcodesED0xca,
		&opcodesED0xcb,
		&opcodesED0xcc,
		&opcodesED0xcd,
		&opcodesED0xce,
		&opcodesED0xcf,
		&opcodesED0xd0,
		&opcodesED0xd1,
		&opcodesED0xd2,
		&opcodesED0xd3,
		&opcodesED0xd4,
		&opcodesED0xd5,
		&opcodesED0xd6,
		&opcodesED0xd7,
		&opcodesED0xd8,
		&opcodesED0xd9,
		&opcodesED0xda,
		&opcodesED0xdb,
		&opcodesED0xdc,
		&opcodesED0xdd,
		&opcodesED0xde,
		&opcodesED0xdf,
		&opcodesED0xe0,
		&opcodesED0xe1,
		&opcodesED0xe2,
		&opcodesED0xe3,
		&opcodesED0xe4,
		&opcodesED0xe5,
		&opcodesED0xe6,
		&opcodesED0xe7,
		&opcodesED0xe8,
		&opcodesED0xe9,
		&opcodesED0xea,
		&opcodesED0xeb,
		&opcodesED0xec,
		&opcodesED0xed,
		&opcodesED0xee,
		&opcodesED0xef,
		&opcodesED0xf0,
		&opcodesED0xf1,
		&opcodesED0xf2,
		&opcodesED0xf3,
		&opcodesED0xf4,
		&opcodesED0xf5,
		&opcodesED0xf6,
		&opcodesED0xf7,
		&opcodesED0xf8,
		&opcodesED0xf9,
		&opcodesED0xfa,
		&opcodesED0xfb,
		&opcodesED0xfc,
		&opcodesED0xfd,
		&opcodesED0xfe,
		&opcodesED0xff
	};
}
