/*
	Autogenerated File (generate_opcodes.py).
*/

#pragma once

#include <stdint.h>
#include "Z80Instructions/Z80Instructions.h"
#include "Z80.h"

namespace Z80Instructions
{
	inline uint8_t opcodesCB0x00(Z80& cpu)
	{
		cpu.RLC(cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x01(Z80& cpu)
	{
		cpu.RLC(cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x02(Z80& cpu)
	{
		cpu.RLC(cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x03(Z80& cpu)
	{
		cpu.RLC(cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x04(Z80& cpu)
	{
		cpu.RLC(cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x05(Z80& cpu)
	{
		cpu.RLC(cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x06(Z80& cpu)
	{
		cpu.RLC_HL();
		return 15;
	};

	inline uint8_t opcodesCB0x07(Z80& cpu)
	{
		cpu.RLC(cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x08(Z80& cpu)
	{
		cpu.RRC(cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x09(Z80& cpu)
	{
		cpu.RRC(cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x0a(Z80& cpu)
	{
		cpu.RRC(cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x0b(Z80& cpu)
	{
		cpu.RRC(cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x0c(Z80& cpu)
	{
		cpu.RRC(cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x0d(Z80& cpu)
	{
		cpu.RRC(cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x0e(Z80& cpu)
	{
		cpu.RRC_HL();
		return 15;
	};

	inline uint8_t opcodesCB0x0f(Z80& cpu)
	{
		cpu.RRC(cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x10(Z80& cpu)
	{
		cpu.RL(cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x11(Z80& cpu)
	{
		cpu.RL(cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x12(Z80& cpu)
	{
		cpu.RL(cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x13(Z80& cpu)
	{
		cpu.RL(cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x14(Z80& cpu)
	{
		cpu.RL(cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x15(Z80& cpu)
	{
		cpu.RL(cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x16(Z80& cpu)
	{
		cpu.RL_HL();
		return 15;
	};

	inline uint8_t opcodesCB0x17(Z80& cpu)
	{
		cpu.RL(cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x18(Z80& cpu)
	{
		cpu.RR(cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x19(Z80& cpu)
	{
		cpu.RR(cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x1a(Z80& cpu)
	{
		cpu.RR(cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x1b(Z80& cpu)
	{
		cpu.RR(cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x1c(Z80& cpu)
	{
		cpu.RR(cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x1d(Z80& cpu)
	{
		cpu.RR(cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x1e(Z80& cpu)
	{
		cpu.RR_HL();
		return 15;
	};

	inline uint8_t opcodesCB0x1f(Z80& cpu)
	{
		cpu.RR(cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x20(Z80& cpu)
	{
		cpu.SLA(cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x21(Z80& cpu)
	{
		cpu.SLA(cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x22(Z80& cpu)
	{
		cpu.SLA(cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x23(Z80& cpu)
	{
		cpu.SLA(cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x24(Z80& cpu)
	{
		cpu.SLA(cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x25(Z80& cpu)
	{
		cpu.SLA(cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x26(Z80& cpu)
	{
		cpu.SLA_HL();
		return 15;
	};

	inline uint8_t opcodesCB0x27(Z80& cpu)
	{
		cpu.SLA(cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x28(Z80& cpu)
	{
		cpu.SRA(cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x29(Z80& cpu)
	{
		cpu.SRA(cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x2a(Z80& cpu)
	{
		cpu.SRA(cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x2b(Z80& cpu)
	{
		cpu.SRA(cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x2c(Z80& cpu)
	{
		cpu.SRA(cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x2d(Z80& cpu)
	{
		cpu.SRA(cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x2e(Z80& cpu)
	{
		cpu.SRA_HL();
		return 15;
	};

	inline uint8_t opcodesCB0x2f(Z80& cpu)
	{
		cpu.SRA(cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x38(Z80& cpu)
	{
		cpu.SRL(cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x39(Z80& cpu)
	{
		cpu.SRL(cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x3a(Z80& cpu)
	{
		cpu.SRL(cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x3b(Z80& cpu)
	{
		cpu.SRL(cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x3c(Z80& cpu)
	{
		cpu.SRL(cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x3d(Z80& cpu)
	{
		cpu.SRL(cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x3e(Z80& cpu)
	{
		cpu.SRL_HL();
		return 15;
	};

	inline uint8_t opcodesCB0x3f(Z80& cpu)
	{
		cpu.SRL(cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x40(Z80& cpu)
	{
		cpu.BIT(0, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x41(Z80& cpu)
	{
		cpu.BIT(0, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x42(Z80& cpu)
	{
		cpu.BIT(0, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x43(Z80& cpu)
	{
		cpu.BIT(0, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x44(Z80& cpu)
	{
		cpu.BIT(0, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x45(Z80& cpu)
	{
		cpu.BIT(0, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x46(Z80& cpu)
	{
		cpu.BIT_HL(0);
		return 12;
	};

	inline uint8_t opcodesCB0x47(Z80& cpu)
	{
		cpu.BIT(0, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x48(Z80& cpu)
	{
		cpu.BIT(1, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x49(Z80& cpu)
	{
		cpu.BIT(1, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x4a(Z80& cpu)
	{
		cpu.BIT(1, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x4b(Z80& cpu)
	{
		cpu.BIT(1, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x4c(Z80& cpu)
	{
		cpu.BIT(1, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x4d(Z80& cpu)
	{
		cpu.BIT(1, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x4e(Z80& cpu)
	{
		cpu.BIT_HL(1);
		return 12;
	};

	inline uint8_t opcodesCB0x4f(Z80& cpu)
	{
		cpu.BIT(1, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x50(Z80& cpu)
	{
		cpu.BIT(2, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x51(Z80& cpu)
	{
		cpu.BIT(2, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x52(Z80& cpu)
	{
		cpu.BIT(2, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x53(Z80& cpu)
	{
		cpu.BIT(2, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x54(Z80& cpu)
	{
		cpu.BIT(2, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x55(Z80& cpu)
	{
		cpu.BIT(2, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x56(Z80& cpu)
	{
		cpu.BIT_HL(2);
		return 12;
	};

	inline uint8_t opcodesCB0x57(Z80& cpu)
	{
		cpu.BIT(2, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x58(Z80& cpu)
	{
		cpu.BIT(3, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x59(Z80& cpu)
	{
		cpu.BIT(3, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x5a(Z80& cpu)
	{
		cpu.BIT(3, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x5b(Z80& cpu)
	{
		cpu.BIT(3, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x5c(Z80& cpu)
	{
		cpu.BIT(3, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x5d(Z80& cpu)
	{
		cpu.BIT(3, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x5e(Z80& cpu)
	{
		cpu.BIT_HL(3);
		return 12;
	};

	inline uint8_t opcodesCB0x5f(Z80& cpu)
	{
		cpu.BIT(3, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x60(Z80& cpu)
	{
		cpu.BIT(4, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x61(Z80& cpu)
	{
		cpu.BIT(4, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x62(Z80& cpu)
	{
		cpu.BIT(4, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x63(Z80& cpu)
	{
		cpu.BIT(4, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x64(Z80& cpu)
	{
		cpu.BIT(4, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x65(Z80& cpu)
	{
		cpu.BIT(4, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x66(Z80& cpu)
	{
		cpu.BIT_HL(4);
		return 12;
	};

	inline uint8_t opcodesCB0x67(Z80& cpu)
	{
		cpu.BIT(4, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x68(Z80& cpu)
	{
		cpu.BIT(5, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x69(Z80& cpu)
	{
		cpu.BIT(5, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x6a(Z80& cpu)
	{
		cpu.BIT(5, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x6b(Z80& cpu)
	{
		cpu.BIT(5, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x6c(Z80& cpu)
	{
		cpu.BIT(5, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x6d(Z80& cpu)
	{
		cpu.BIT(5, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x6e(Z80& cpu)
	{
		cpu.BIT_HL(5);
		return 12;
	};

	inline uint8_t opcodesCB0x6f(Z80& cpu)
	{
		cpu.BIT(5, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x70(Z80& cpu)
	{
		cpu.BIT(6, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x71(Z80& cpu)
	{
		cpu.BIT(6, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x72(Z80& cpu)
	{
		cpu.BIT(6, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x73(Z80& cpu)
	{
		cpu.BIT(6, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x74(Z80& cpu)
	{
		cpu.BIT(6, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x75(Z80& cpu)
	{
		cpu.BIT(6, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x76(Z80& cpu)
	{
		cpu.BIT_HL(6);
		return 12;
	};

	inline uint8_t opcodesCB0x77(Z80& cpu)
	{
		cpu.BIT(6, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x78(Z80& cpu)
	{
		cpu.BIT(7, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x79(Z80& cpu)
	{
		cpu.BIT(7, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x7a(Z80& cpu)
	{
		cpu.BIT(7, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x7b(Z80& cpu)
	{
		cpu.BIT(7, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x7c(Z80& cpu)
	{
		cpu.BIT(7, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x7d(Z80& cpu)
	{
		cpu.BIT(7, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x7e(Z80& cpu)
	{
		cpu.BIT_HL(7);
		return 12;
	};

	inline uint8_t opcodesCB0x7f(Z80& cpu)
	{
		cpu.BIT(7, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x80(Z80& cpu)
	{
		cpu.RES(0, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x81(Z80& cpu)
	{
		cpu.RES(0, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x82(Z80& cpu)
	{
		cpu.RES(0, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x83(Z80& cpu)
	{
		cpu.RES(0, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x84(Z80& cpu)
	{
		cpu.RES(0, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x85(Z80& cpu)
	{
		cpu.RES(0, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x86(Z80& cpu)
	{
		cpu.RES_HL(0);
		return 15;
	};

	inline uint8_t opcodesCB0x87(Z80& cpu)
	{
		cpu.RES(0, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x88(Z80& cpu)
	{
		cpu.RES(1, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x89(Z80& cpu)
	{
		cpu.RES(1, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x8a(Z80& cpu)
	{
		cpu.RES(1, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x8b(Z80& cpu)
	{
		cpu.RES(1, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x8c(Z80& cpu)
	{
		cpu.RES(1, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x8d(Z80& cpu)
	{
		cpu.RES(1, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x8e(Z80& cpu)
	{
		cpu.RES_HL(1);
		return 15;
	};

	inline uint8_t opcodesCB0x8f(Z80& cpu)
	{
		cpu.RES(1, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x90(Z80& cpu)
	{
		cpu.RES(2, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x91(Z80& cpu)
	{
		cpu.RES(2, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x92(Z80& cpu)
	{
		cpu.RES(2, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x93(Z80& cpu)
	{
		cpu.RES(2, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x94(Z80& cpu)
	{
		cpu.RES(2, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x95(Z80& cpu)
	{
		cpu.RES(2, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x96(Z80& cpu)
	{
		cpu.RES_HL(2);
		return 15;
	};

	inline uint8_t opcodesCB0x97(Z80& cpu)
	{
		cpu.RES(2, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x98(Z80& cpu)
	{
		cpu.RES(3, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x99(Z80& cpu)
	{
		cpu.RES(3, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x9a(Z80& cpu)
	{
		cpu.RES(3, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0x9b(Z80& cpu)
	{
		cpu.RES(3, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0x9c(Z80& cpu)
	{
		cpu.RES(3, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0x9d(Z80& cpu)
	{
		cpu.RES(3, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0x9e(Z80& cpu)
	{
		cpu.RES_HL(3);
		return 15;
	};

	inline uint8_t opcodesCB0x9f(Z80& cpu)
	{
		cpu.RES(3, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xa0(Z80& cpu)
	{
		cpu.RES(4, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xa1(Z80& cpu)
	{
		cpu.RES(4, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xa2(Z80& cpu)
	{
		cpu.RES(4, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xa3(Z80& cpu)
	{
		cpu.RES(4, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xa4(Z80& cpu)
	{
		cpu.RES(4, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xa5(Z80& cpu)
	{
		cpu.RES(4, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xa6(Z80& cpu)
	{
		cpu.RES_HL(4);
		return 15;
	};

	inline uint8_t opcodesCB0xa7(Z80& cpu)
	{
		cpu.RES(4, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xa8(Z80& cpu)
	{
		cpu.RES(5, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xa9(Z80& cpu)
	{
		cpu.RES(5, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xaa(Z80& cpu)
	{
		cpu.RES(5, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xab(Z80& cpu)
	{
		cpu.RES(5, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xac(Z80& cpu)
	{
		cpu.RES(5, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xad(Z80& cpu)
	{
		cpu.RES(5, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xae(Z80& cpu)
	{
		cpu.RES_HL(5);
		return 15;
	};

	inline uint8_t opcodesCB0xaf(Z80& cpu)
	{
		cpu.RES(5, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xb0(Z80& cpu)
	{
		cpu.RES(6, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xb1(Z80& cpu)
	{
		cpu.RES(6, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xb2(Z80& cpu)
	{
		cpu.RES(6, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xb3(Z80& cpu)
	{
		cpu.RES(6, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xb4(Z80& cpu)
	{
		cpu.RES(6, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xb5(Z80& cpu)
	{
		cpu.RES(6, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xb6(Z80& cpu)
	{
		cpu.RES_HL(6);
		return 15;
	};

	inline uint8_t opcodesCB0xb7(Z80& cpu)
	{
		cpu.RES(6, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xb8(Z80& cpu)
	{
		cpu.RES(7, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xb9(Z80& cpu)
	{
		cpu.RES(7, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xba(Z80& cpu)
	{
		cpu.RES(7, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xbb(Z80& cpu)
	{
		cpu.RES(7, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xbc(Z80& cpu)
	{
		cpu.RES(7, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xbd(Z80& cpu)
	{
		cpu.RES(7, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xbe(Z80& cpu)
	{
		cpu.RES_HL(7);
		return 15;
	};

	inline uint8_t opcodesCB0xbf(Z80& cpu)
	{
		cpu.RES(7, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xc0(Z80& cpu)
	{
		cpu.SET(0, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xc1(Z80& cpu)
	{
		cpu.SET(0, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xc2(Z80& cpu)
	{
		cpu.SET(0, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xc3(Z80& cpu)
	{
		cpu.SET(0, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xc4(Z80& cpu)
	{
		cpu.SET(0, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xc5(Z80& cpu)
	{
		cpu.SET(0, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xc6(Z80& cpu)
	{
		cpu.SET_HL(0);
		return 15;
	};

	inline uint8_t opcodesCB0xc7(Z80& cpu)
	{
		cpu.SET(0, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xc8(Z80& cpu)
	{
		cpu.SET(1, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xc9(Z80& cpu)
	{
		cpu.SET(1, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xca(Z80& cpu)
	{
		cpu.SET(1, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xcb(Z80& cpu)
	{
		cpu.SET(1, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xcc(Z80& cpu)
	{
		cpu.SET(1, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xcd(Z80& cpu)
	{
		cpu.SET(1, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xce(Z80& cpu)
	{
		cpu.SET_HL(1);
		return 15;
	};

	inline uint8_t opcodesCB0xcf(Z80& cpu)
	{
		cpu.SET(1, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xd0(Z80& cpu)
	{
		cpu.SET(2, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xd1(Z80& cpu)
	{
		cpu.SET(2, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xd2(Z80& cpu)
	{
		cpu.SET(2, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xd3(Z80& cpu)
	{
		cpu.SET(2, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xd4(Z80& cpu)
	{
		cpu.SET(2, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xd5(Z80& cpu)
	{
		cpu.SET(2, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xd6(Z80& cpu)
	{
		cpu.SET_HL(2);
		return 15;
	};

	inline uint8_t opcodesCB0xd7(Z80& cpu)
	{
		cpu.SET(2, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xd8(Z80& cpu)
	{
		cpu.SET(3, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xd9(Z80& cpu)
	{
		cpu.SET(3, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xda(Z80& cpu)
	{
		cpu.SET(3, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xdb(Z80& cpu)
	{
		cpu.SET(3, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xdc(Z80& cpu)
	{
		cpu.SET(3, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xdd(Z80& cpu)
	{
		cpu.SET(3, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xde(Z80& cpu)
	{
		cpu.SET_HL(3);
		return 15;
	};

	inline uint8_t opcodesCB0xdf(Z80& cpu)
	{
		cpu.SET(3, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xe0(Z80& cpu)
	{
		cpu.SET(4, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xe1(Z80& cpu)
	{
		cpu.SET(4, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xe2(Z80& cpu)
	{
		cpu.SET(4, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xe3(Z80& cpu)
	{
		cpu.SET(4, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xe4(Z80& cpu)
	{
		cpu.SET(4, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xe5(Z80& cpu)
	{
		cpu.SET(4, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xe6(Z80& cpu)
	{
		cpu.SET_HL(4);
		return 15;
	};

	inline uint8_t opcodesCB0xe7(Z80& cpu)
	{
		cpu.SET(4, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xe8(Z80& cpu)
	{
		cpu.SET(5, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xe9(Z80& cpu)
	{
		cpu.SET(5, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xea(Z80& cpu)
	{
		cpu.SET(5, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xeb(Z80& cpu)
	{
		cpu.SET(5, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xec(Z80& cpu)
	{
		cpu.SET(5, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xed(Z80& cpu)
	{
		cpu.SET(5, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xee(Z80& cpu)
	{
		cpu.SET_HL(5);
		return 15;
	};

	inline uint8_t opcodesCB0xef(Z80& cpu)
	{
		cpu.SET(5, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xf0(Z80& cpu)
	{
		cpu.SET(6, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xf1(Z80& cpu)
	{
		cpu.SET(6, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xf2(Z80& cpu)
	{
		cpu.SET(6, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xf3(Z80& cpu)
	{
		cpu.SET(6, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xf4(Z80& cpu)
	{
		cpu.SET(6, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xf5(Z80& cpu)
	{
		cpu.SET(6, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xf6(Z80& cpu)
	{
		cpu.SET_HL(6);
		return 15;
	};

	inline uint8_t opcodesCB0xf7(Z80& cpu)
	{
		cpu.SET(6, cpu.m_reg_AF.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xf8(Z80& cpu)
	{
		cpu.SET(7, cpu.m_reg_BC.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xf9(Z80& cpu)
	{
		cpu.SET(7, cpu.m_reg_BC.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xfa(Z80& cpu)
	{
		cpu.SET(7, cpu.m_reg_DE.hi);
		return 8;
	};

	inline uint8_t opcodesCB0xfb(Z80& cpu)
	{
		cpu.SET(7, cpu.m_reg_DE.lo);
		return 8;
	};

	inline uint8_t opcodesCB0xfc(Z80& cpu)
	{
		cpu.SET(7, cpu.GetPrefixedHL().hi);
		return 8;
	};

	inline uint8_t opcodesCB0xfd(Z80& cpu)
	{
		cpu.SET(7, cpu.GetPrefixedHL().lo);
		return 8;
	};

	inline uint8_t opcodesCB0xfe(Z80& cpu)
	{
		cpu.SET_HL(7);
		return 15;
	};

	inline uint8_t opcodesCB0xff(Z80& cpu)
	{
		cpu.SET(7, cpu.m_reg_AF.hi);
		return 8;
	};

	OPCodeFunc s_opcode_cb_funcs [256] = 
	{
		&opcodesCB0x00,
		&opcodesCB0x01,
		&opcodesCB0x02,
		&opcodesCB0x03,
		&opcodesCB0x04,
		&opcodesCB0x05,
		&opcodesCB0x06,
		&opcodesCB0x07,
		&opcodesCB0x08,
		&opcodesCB0x09,
		&opcodesCB0x0a,
		&opcodesCB0x0b,
		&opcodesCB0x0c,
		&opcodesCB0x0d,
		&opcodesCB0x0e,
		&opcodesCB0x0f,
		&opcodesCB0x10,
		&opcodesCB0x11,
		&opcodesCB0x12,
		&opcodesCB0x13,
		&opcodesCB0x14,
		&opcodesCB0x15,
		&opcodesCB0x16,
		&opcodesCB0x17,
		&opcodesCB0x18,
		&opcodesCB0x19,
		&opcodesCB0x1a,
		&opcodesCB0x1b,
		&opcodesCB0x1c,
		&opcodesCB0x1d,
		&opcodesCB0x1e,
		&opcodesCB0x1f,
		&opcodesCB0x20,
		&opcodesCB0x21,
		&opcodesCB0x22,
		&opcodesCB0x23,
		&opcodesCB0x24,
		&opcodesCB0x25,
		&opcodesCB0x26,
		&opcodesCB0x27,
		&opcodesCB0x28,
		&opcodesCB0x29,
		&opcodesCB0x2a,
		&opcodesCB0x2b,
		&opcodesCB0x2c,
		&opcodesCB0x2d,
		&opcodesCB0x2e,
		&opcodesCB0x2f,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&opcodesCB0x38,
		&opcodesCB0x39,
		&opcodesCB0x3a,
		&opcodesCB0x3b,
		&opcodesCB0x3c,
		&opcodesCB0x3d,
		&opcodesCB0x3e,
		&opcodesCB0x3f,
		&opcodesCB0x40,
		&opcodesCB0x41,
		&opcodesCB0x42,
		&opcodesCB0x43,
		&opcodesCB0x44,
		&opcodesCB0x45,
		&opcodesCB0x46,
		&opcodesCB0x47,
		&opcodesCB0x48,
		&opcodesCB0x49,
		&opcodesCB0x4a,
		&opcodesCB0x4b,
		&opcodesCB0x4c,
		&opcodesCB0x4d,
		&opcodesCB0x4e,
		&opcodesCB0x4f,
		&opcodesCB0x50,
		&opcodesCB0x51,
		&opcodesCB0x52,
		&opcodesCB0x53,
		&opcodesCB0x54,
		&opcodesCB0x55,
		&opcodesCB0x56,
		&opcodesCB0x57,
		&opcodesCB0x58,
		&opcodesCB0x59,
		&opcodesCB0x5a,
		&opcodesCB0x5b,
		&opcodesCB0x5c,
		&opcodesCB0x5d,
		&opcodesCB0x5e,
		&opcodesCB0x5f,
		&opcodesCB0x60,
		&opcodesCB0x61,
		&opcodesCB0x62,
		&opcodesCB0x63,
		&opcodesCB0x64,
		&opcodesCB0x65,
		&opcodesCB0x66,
		&opcodesCB0x67,
		&opcodesCB0x68,
		&opcodesCB0x69,
		&opcodesCB0x6a,
		&opcodesCB0x6b,
		&opcodesCB0x6c,
		&opcodesCB0x6d,
		&opcodesCB0x6e,
		&opcodesCB0x6f,
		&opcodesCB0x70,
		&opcodesCB0x71,
		&opcodesCB0x72,
		&opcodesCB0x73,
		&opcodesCB0x74,
		&opcodesCB0x75,
		&opcodesCB0x76,
		&opcodesCB0x77,
		&opcodesCB0x78,
		&opcodesCB0x79,
		&opcodesCB0x7a,
		&opcodesCB0x7b,
		&opcodesCB0x7c,
		&opcodesCB0x7d,
		&opcodesCB0x7e,
		&opcodesCB0x7f,
		&opcodesCB0x80,
		&opcodesCB0x81,
		&opcodesCB0x82,
		&opcodesCB0x83,
		&opcodesCB0x84,
		&opcodesCB0x85,
		&opcodesCB0x86,
		&opcodesCB0x87,
		&opcodesCB0x88,
		&opcodesCB0x89,
		&opcodesCB0x8a,
		&opcodesCB0x8b,
		&opcodesCB0x8c,
		&opcodesCB0x8d,
		&opcodesCB0x8e,
		&opcodesCB0x8f,
		&opcodesCB0x90,
		&opcodesCB0x91,
		&opcodesCB0x92,
		&opcodesCB0x93,
		&opcodesCB0x94,
		&opcodesCB0x95,
		&opcodesCB0x96,
		&opcodesCB0x97,
		&opcodesCB0x98,
		&opcodesCB0x99,
		&opcodesCB0x9a,
		&opcodesCB0x9b,
		&opcodesCB0x9c,
		&opcodesCB0x9d,
		&opcodesCB0x9e,
		&opcodesCB0x9f,
		&opcodesCB0xa0,
		&opcodesCB0xa1,
		&opcodesCB0xa2,
		&opcodesCB0xa3,
		&opcodesCB0xa4,
		&opcodesCB0xa5,
		&opcodesCB0xa6,
		&opcodesCB0xa7,
		&opcodesCB0xa8,
		&opcodesCB0xa9,
		&opcodesCB0xaa,
		&opcodesCB0xab,
		&opcodesCB0xac,
		&opcodesCB0xad,
		&opcodesCB0xae,
		&opcodesCB0xaf,
		&opcodesCB0xb0,
		&opcodesCB0xb1,
		&opcodesCB0xb2,
		&opcodesCB0xb3,
		&opcodesCB0xb4,
		&opcodesCB0xb5,
		&opcodesCB0xb6,
		&opcodesCB0xb7,
		&opcodesCB0xb8,
		&opcodesCB0xb9,
		&opcodesCB0xba,
		&opcodesCB0xbb,
		&opcodesCB0xbc,
		&opcodesCB0xbd,
		&opcodesCB0xbe,
		&opcodesCB0xbf,
		&opcodesCB0xc0,
		&opcodesCB0xc1,
		&opcodesCB0xc2,
		&opcodesCB0xc3,
		&opcodesCB0xc4,
		&opcodesCB0xc5,
		&opcodesCB0xc6,
		&opcodesCB0xc7,
		&opcodesCB0xc8,
		&opcodesCB0xc9,
		&opcodesCB0xca,
		&opcodesCB0xcb,
		&opcodesCB0xcc,
		&opcodesCB0xcd,
		&opcodesCB0xce,
		&opcodesCB0xcf,
		&opcodesCB0xd0,
		&opcodesCB0xd1,
		&opcodesCB0xd2,
		&opcodesCB0xd3,
		&opcodesCB0xd4,
		&opcodesCB0xd5,
		&opcodesCB0xd6,
		&opcodesCB0xd7,
		&opcodesCB0xd8,
		&opcodesCB0xd9,
		&opcodesCB0xda,
		&opcodesCB0xdb,
		&opcodesCB0xdc,
		&opcodesCB0xdd,
		&opcodesCB0xde,
		&opcodesCB0xdf,
		&opcodesCB0xe0,
		&opcodesCB0xe1,
		&opcodesCB0xe2,
		&opcodesCB0xe3,
		&opcodesCB0xe4,
		&opcodesCB0xe5,
		&opcodesCB0xe6,
		&opcodesCB0xe7,
		&opcodesCB0xe8,
		&opcodesCB0xe9,
		&opcodesCB0xea,
		&opcodesCB0xeb,
		&opcodesCB0xec,
		&opcodesCB0xed,
		&opcodesCB0xee,
		&opcodesCB0xef,
		&opcodesCB0xf0,
		&opcodesCB0xf1,
		&opcodesCB0xf2,
		&opcodesCB0xf3,
		&opcodesCB0xf4,
		&opcodesCB0xf5,
		&opcodesCB0xf6,
		&opcodesCB0xf7,
		&opcodesCB0xf8,
		&opcodesCB0xf9,
		&opcodesCB0xfa,
		&opcodesCB0xfb,
		&opcodesCB0xfc,
		&opcodesCB0xfd,
		&opcodesCB0xfe,
		&opcodesCB0xff
	};
}
