/*
	Autogenerated File (generate_opcodes.py).
*/

#pragma once

#include <stdint.h>
#include "Z80Instructions/Z80Instructions.h"
#include "Z80.h"

namespace Z80Instructions
{
	inline uint8_t opcodesED0x40(Z80& cpu)
	{
		cpu.IN(cpu.m_reg_BC.hi);
		return 12;
	};

	inline uint8_t opcodesED0x41(Z80& cpu)
	{
		cpu.OUT(cpu.m_reg_BC.lo, cpu.m_reg_BC.hi);
		return 12;
	};

	inline uint8_t opcodesED0x42(Z80& cpu)
	{
		cpu.SBC(cpu.m_reg_BC.value);
		return 15;
	};

	inline uint8_t opcodesED0x43(Z80& cpu)
	{
		cpu.LD_NNDD(cpu.m_reg_BC);
		return 20;
	};

	inline uint8_t opcodesED0x44(Z80& cpu)
	{
		cpu.NEG();
		return 8;
	};

	inline uint8_t opcodesED0x45(Z80& cpu)
	{
		cpu.RETN();
		return 14;
	};

	inline uint8_t opcodesED0x46(Z80& cpu)
	{
		cpu.IM0();
		return 8;
	};

	inline uint8_t opcodesED0x47(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_interrupt, cpu.m_reg_AF.hi);
		return 9;
	};

	inline uint8_t opcodesED0x48(Z80& cpu)
	{
		cpu.IN(cpu.m_reg_BC.lo);
		return 12;
	};

	inline uint8_t opcodesED0x49(Z80& cpu)
	{
		cpu.OUT(cpu.m_reg_BC.lo, cpu.m_reg_BC.lo);
		return 12;
	};

	inline uint8_t opcodesED0x4a(Z80& cpu)
	{
		cpu.ADC(cpu.m_reg_BC.value);
		return 15;
	};

	inline uint8_t opcodesED0x4b(Z80& cpu)
	{
		cpu.LD_DDNN(cpu.m_reg_BC);
		return 20;
	};

	inline uint8_t opcodesED0x4d(Z80& cpu)
	{
		cpu.RETI();
		return 14;
	};

	inline uint8_t opcodesED0x4f(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_refresh, cpu.m_reg_AF.hi);
		return 9;
	};

	inline uint8_t opcodesED0x50(Z80& cpu)
	{
		cpu.IN(cpu.m_reg_DE.hi, cpu.m_reg_BC.lo);
		return 12;
	};

	inline uint8_t opcodesED0x51(Z80& cpu)
	{
		cpu.OUT(cpu.m_reg_BC.lo, cpu.m_reg_DE.hi);
		return 12;
	};

	inline uint8_t opcodesED0x52(Z80& cpu)
	{
		cpu.SBC(cpu.m_reg_DE.value);
		return 15;
	};

	inline uint8_t opcodesED0x53(Z80& cpu)
	{
		cpu.LD_NNDD(cpu.m_reg_DE);
		return 20;
	};

	inline uint8_t opcodesED0x56(Z80& cpu)
	{
		cpu.IM1();
		return 8;
	};

	inline uint8_t opcodesED0x57(Z80& cpu)
	{
		cpu.LD_AI();
		return 9;
	};

	inline uint8_t opcodesED0x58(Z80& cpu)
	{
		cpu.IN(cpu.m_reg_DE.lo, cpu.m_reg_BC.lo);
		return 12;
	};

	inline uint8_t opcodesED0x59(Z80& cpu)
	{
		cpu.OUT(cpu.m_reg_BC.lo, cpu.m_reg_DE.lo);
		return 12;
	};

	inline uint8_t opcodesED0x5a(Z80& cpu)
	{
		cpu.ADD(cpu.m_reg_BC.value);
		return 15;
	};

	inline uint8_t opcodesED0x5b(Z80& cpu)
	{
		cpu.LD_DDNN(cpu.m_reg_BC);
		return 20;
	};

	inline uint8_t opcodesED0x5e(Z80& cpu)
	{
		cpu.IM2();
		return 8;
	};

	inline uint8_t opcodesED0x5f(Z80& cpu)
	{
		cpu.LD_AR();
		return 9;
	};

	inline uint8_t opcodesED0x60(Z80& cpu)
	{
		cpu.IN(cpu.m_reg_HL.hi, cpu.m_reg_BC.lo);
		return 12;
	};

	inline uint8_t opcodesED0x61(Z80& cpu)
	{
		cpu.OUT(cpu.m_reg_BC.lo, cpu.m_reg_HL.hi);
		return 12;
	};

	inline uint8_t opcodesED0x62(Z80& cpu)
	{
		cpu.SBC_HL(cpu.m_reg_HL.value);
		return 15;
	};

	inline uint8_t opcodesED0x63(Z80& cpu)
	{
		cpu.LD_NNDD(cpu.m_reg_HL.value);
		return 20;
	};

	inline uint8_t opcodesED0x67(Z80& cpu)
	{
		cpu.RRD();
		return 18;
	};

	inline uint8_t opcodesED0x68(Z80& cpu)
	{
		cpu.IN(cpu.m_reg_HL.lo, cpu.m_reg_BC.lo);
		return 12;
	};

	inline uint8_t opcodesED0x69(Z80& cpu)
	{
		cpu.OUT(cpu.m_reg_BC.lo, cpu.m_reg_HL.lo);
		return 12;
	};

	inline uint8_t opcodesED0x6a(Z80& cpu)
	{
		cpu.ADC_HL(cpu.m_reg_HL.value);
		return 15;
	};

	inline uint8_t opcodesED0x6b(Z80& cpu)
	{
		cpu.LD_DDNN(cpu.m_reg_HL);
		return 20;
	};

	inline uint8_t opcodesED0x6f(Z80& cpu)
	{
		cpu.RLD();
		return 18;
	};

	inline uint8_t opcodesED0x72(Z80& cpu)
	{
		cpu.SBC(cpu.m_stack_pointer);
		return 15;
	};

	inline uint8_t opcodesED0x73(Z80& cpu)
	{
		cpu.LD_NNDD(cpu.m_stack_pointer);
		return 20;
	};

	inline uint8_t opcodesED0x78(Z80& cpu)
	{
		cpu.IN(cpu.m_reg_AF.hi, cpu.m_reg_BC.lo);
		return 12;
	};

	inline uint8_t opcodesED0x79(Z80& cpu)
	{
		cpu.OUT(cpu.m_reg_BC.lo, cpu.m_reg_AF.hi);
		return 12;
	};

	inline uint8_t opcodesED0x7a(Z80& cpu)
	{
		cpu.ADC(cpu.m_stack_pointer);
		return 15;
	};

	inline uint8_t opcodesED0x7b(Z80& cpu)
	{
		cpu.LD_DDNN(cpu.m_stack_pointer);
		return 20;
	};

	inline uint8_t opcodesED0xa0(Z80& cpu)
	{
		cpu.LDI();
		return 16;
	};

	inline uint8_t opcodesED0xa1(Z80& cpu)
	{
		cpu.CPI();
		return 16;
	};

	inline uint8_t opcodesED0xa2(Z80& cpu)
	{
		cpu.INI();
		return 16;
	};

	inline uint8_t opcodesED0xa3(Z80& cpu)
	{
		cpu.OUTI();
		return 16;
	};

	inline uint8_t opcodesED0xa8(Z80& cpu)
	{
		cpu.LDD();
		return 16;
	};

	inline uint8_t opcodesED0xa9(Z80& cpu)
	{
		cpu.CPD();
		return 16;
	};

	inline uint8_t opcodesED0xaa(Z80& cpu)
	{
		cpu.IND();
		return 16;
	};

	inline uint8_t opcodesED0xab(Z80& cpu)
	{
		cpu.OUTD();
		return 16;
	};

	inline uint8_t opcodesED0xb0(Z80& cpu)
	{
		return 21 ? cpu.LDIR() : 16;
	};

	inline uint8_t opcodesED0xb1(Z80& cpu)
	{
		return 21 ? cpu.CPIR() : 16;
	};

	inline uint8_t opcodesED0xb2(Z80& cpu)
	{
		return 21 ? cpu.INIR() : 16;
	};

	inline uint8_t opcodesED0xb3(Z80& cpu)
	{
		return 21 ? cpu.OTIR() : 16;
	};

	inline uint8_t opcodesED0xb8(Z80& cpu)
	{
		return 21 ? cpu.LDDR() : 16;
	};

	inline uint8_t opcodesED0xb9(Z80& cpu)
	{
		return 21 ? cpu.CPDR() : 16;
	};

	inline uint8_t opcodesED0xba(Z80& cpu)
	{
		return 21 ? cpu.INDR() : 16;
	};

	inline uint8_t opcodesED0xbb(Z80& cpu)
	{
		return 21 ? cpu.OUTR() : 16;
	};

	OPCodeFunc s_opcode_ed_funcs [256] = 
	{
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&opcodesED0x40,
		&opcodesED0x41,
		&opcodesED0x42,
		&opcodesED0x43,
		&opcodesED0x44,
		&opcodesED0x45,
		&opcodesED0x46,
		&opcodesED0x47,
		&opcodesED0x48,
		&opcodesED0x49,
		&opcodesED0x4a,
		&opcodesED0x4b,
		&UnexpectedOPCode,
		&opcodesED0x4d,
		&UnexpectedOPCode,
		&opcodesED0x4f,
		&opcodesED0x50,
		&opcodesED0x51,
		&opcodesED0x52,
		&opcodesED0x53,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&opcodesED0x56,
		&opcodesED0x57,
		&opcodesED0x58,
		&opcodesED0x59,
		&opcodesED0x5a,
		&opcodesED0x5b,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&opcodesED0x5e,
		&opcodesED0x5f,
		&opcodesED0x60,
		&opcodesED0x61,
		&opcodesED0x62,
		&opcodesED0x63,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&opcodesED0x67,
		&opcodesED0x68,
		&opcodesED0x69,
		&opcodesED0x6a,
		&opcodesED0x6b,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&opcodesED0x6f,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&opcodesED0x72,
		&opcodesED0x73,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&opcodesED0x78,
		&opcodesED0x79,
		&opcodesED0x7a,
		&opcodesED0x7b,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&opcodesED0xa0,
		&opcodesED0xa1,
		&opcodesED0xa2,
		&opcodesED0xa3,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&opcodesED0xa8,
		&opcodesED0xa9,
		&opcodesED0xaa,
		&opcodesED0xab,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&opcodesED0xb0,
		&opcodesED0xb1,
		&opcodesED0xb2,
		&opcodesED0xb3,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&opcodesED0xb8,
		&opcodesED0xb9,
		&opcodesED0xba,
		&opcodesED0xbb,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
		&UnexpectedOPCode,
	};
}
