/*
	Autogenerated File (generate_opcodes.py).
*/

#pragma once

#include <stdint.h>
#include "Z80.h"

namespace Z80Instructions
{
	inline uint8_t opcodes0x00(Z80& cpu)
	{
		cpu.NOP();
		return 4;
	};

	inline uint8_t opcodes0x01(Z80& cpu)
	{
		cpu.LD_DDNN(cpu.m_reg_BC);
		return 10;
	};

	inline uint8_t opcodes0x02(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.value, cpu.m_reg_AF.hi);
		return 7;
	};

	inline uint8_t opcodes0x03(Z80& cpu)
	{
		cpu.INC(cpu.m_reg_BC);
		return 6;
	};

	inline uint8_t opcodes0x04(Z80& cpu)
	{
		cpu.INC(cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0x05(Z80& cpu)
	{
		cpu.DEC(cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0x06(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.hi, cpu.ReadByte());
		return 7;
	};

	inline uint8_t opcodes0x07(Z80& cpu)
	{
		cpu.RLCA();
		return 4;
	};

	inline uint8_t opcodes0x08(Z80& cpu)
	{
		cpu.EX(cpu.m_reg_AF, cpu.m_reg_AF_shadow);
		return 4;
	};

	inline uint8_t opcodes0x09(Z80& cpu)
	{
		cpu.ADD(cpu.m_reg_BC.value);
		return 11;
	};

	inline uint8_t opcodes0x0a(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_AF.hi, cpu.m_reg_BC.value);
		return 7;
	};

	inline uint8_t opcodes0x0b(Z80& cpu)
	{
		cpu.DEC(cpu.m_reg_BC);
		return 6;
	};

	inline uint8_t opcodes0x0c(Z80& cpu)
	{
		cpu.INC(cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0x0d(Z80& cpu)
	{
		cpu.DEC(cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0x0e(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.lo, cpu.ReadByte());
		return 7;
	};

	inline uint8_t opcodes0x0f(Z80& cpu)
	{
		cpu.RRCA();
		return 4;
	};

	inline uint8_t opcodes0x10(Z80& cpu)
	{
		return 13 ? cpu.DJNZ() : 8;
	};

	inline uint8_t opcodes0x11(Z80& cpu)
	{
		cpu.LD_DDNN(cpu.m_reg_DE);
		return 10;
	};

	inline uint8_t opcodes0x12(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.value, cpu.m_reg_AF.hi);
		return 7;
	};

	inline uint8_t opcodes0x13(Z80& cpu)
	{
		cpu.INC(cpu.m_reg_DE);
		return 6;
	};

	inline uint8_t opcodes0x14(Z80& cpu)
	{
		cpu.INC(cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0x15(Z80& cpu)
	{
		cpu.DEC(cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0x16(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.hi, cpu.ReadByte());
		return 7;
	};

	inline uint8_t opcodes0x17(Z80& cpu)
	{
		cpu.RLA();
		return 4;
	};

	inline uint8_t opcodes0x18(Z80& cpu)
	{
		cpu.JR();
		return 12;
	};

	inline uint8_t opcodes0x19(Z80& cpu)
	{
		cpu.ADD(cpu.m_reg_DE.value);
		return 11;
	};

	inline uint8_t opcodes0x1a(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_AF.hi, cpu.m_reg_DE.value);
		return 7;
	};

	inline uint8_t opcodes0x1b(Z80& cpu)
	{
		cpu.DEC(cpu.m_reg_DE);
		return 6;
	};

	inline uint8_t opcodes0x1c(Z80& cpu)
	{
		cpu.INC(cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0x1d(Z80& cpu)
	{
		cpu.DEC(cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0x1e(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.lo, cpu.ReadByte());
		return 7;
	};

	inline uint8_t opcodes0x1f(Z80& cpu)
	{
		cpu.RRA();
		return 4;
	};

	inline uint8_t opcodes0x20(Z80& cpu)
	{
		return 12 ? cpu.JR(!cpu.ReadFlag(FLAG::ZERO)) : 7;
	};

	inline uint8_t opcodes0x21(Z80& cpu)
	{
		cpu.LD_DDNN(cpu.GetPrefixedHL());
		return 10;
	};

	inline uint8_t opcodes0x22(Z80& cpu)
	{
		cpu.LD_NNDD(cpu.GetPrefixedHL());
		return 16;
	};

	inline uint8_t opcodes0x23(Z80& cpu)
	{
		cpu.INC(cpu.GetPrefixedHL());
		return 6;
	};

	inline uint8_t opcodes0x24(Z80& cpu)
	{
		cpu.INC(cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0x25(Z80& cpu)
	{
		cpu.DEC(cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0x26(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().hi, cpu.ReadByte());
		return 7;
	};

	inline uint8_t opcodes0x27(Z80& cpu)
	{
		cpu.DAA();
		return 4;
	};

	inline uint8_t opcodes0x28(Z80& cpu)
	{
		return 12 ? cpu.JR(cpu.ReadFlag(FLAG::ZERO)) : 7;
	};

	inline uint8_t opcodes0x29(Z80& cpu)
	{
		cpu.ADD(cpu.GetPrefixedHLAddress());
		return 11;
	};

	inline uint8_t opcodes0x2a(Z80& cpu)
	{
		cpu.LD_DDNN(cpu.GetPrefixedHL());
		return 16;
	};

	inline uint8_t opcodes0x2b(Z80& cpu)
	{
		cpu.DEC(cpu.GetPrefixedHL());
		return 6;
	};

	inline uint8_t opcodes0x2c(Z80& cpu)
	{
		cpu.INC(cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0x2d(Z80& cpu)
	{
		cpu.DEC(cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0x2e(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().lo, cpu.ReadByte());
		return 7;
	};

	inline uint8_t opcodes0x2f(Z80& cpu)
	{
		cpu.CPL();
		return 4;
	};

	inline uint8_t opcodes0x30(Z80& cpu)
	{
		return 12 ? cpu.JR(!cpu.ReadFlag(FLAG::CARRY)) : 7;
	};

	inline uint8_t opcodes0x31(Z80& cpu)
	{
		cpu.LD_DDNN(cpu.m_stack_pointer);
		return 10;
	};

	inline uint8_t opcodes0x32(Z80& cpu)
	{
		cpu.LD_NNDD(cpu.m_reg_AF.hi);
		return 13;
	};

	inline uint8_t opcodes0x33(Z80& cpu)
	{
		cpu.INC(cpu.m_stack_pointer);
		return 6;
	};

	inline uint8_t opcodes0x34(Z80& cpu)
	{
		cpu.INC_HL();
		return 11;
	};

	inline uint8_t opcodes0x35(Z80& cpu)
	{
		cpu.DEC_HL();
		return 11;
	};

	inline uint8_t opcodes0x36(Z80& cpu)
	{
		cpu.LD_HL_N();
		return 10;
	};

	inline uint8_t opcodes0x37(Z80& cpu)
	{
		cpu.SCF();
		return 4;
	};

	inline uint8_t opcodes0x38(Z80& cpu)
	{
		return 12 ? cpu.JR(cpu.ReadFlag(FLAG::CARRY)) : 7;
	};

	inline uint8_t opcodes0x39(Z80& cpu)
	{
		cpu.ADD(cpu.m_stack_pointer);
		return 11;
	};

	inline uint8_t opcodes0x3a(Z80& cpu)
	{
		cpu.LD_DDNN(cpu.m_reg_AF.hi);
		return 13;
	};

	inline uint8_t opcodes0x3b(Z80& cpu)
	{
		cpu.DEC(cpu.m_stack_pointer);
		return 6;
	};

	inline uint8_t opcodes0x3c(Z80& cpu)
	{
		cpu.INC(cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0x3d(Z80& cpu)
	{
		cpu.DEC(cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0x3e(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_AF.hi, cpu.ReadByte());
		return 7;
	};

	inline uint8_t opcodes0x3f(Z80& cpu)
	{
		cpu.CCF();
		return 4;
	};

	inline uint8_t opcodes0x40(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.hi, cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0x41(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.hi, cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0x42(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.hi, cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0x43(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.hi, cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0x44(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.hi, cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0x45(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.hi, cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0x46(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.hi, cpu.GetPrefixedHLAddress());
		return 7;
	};

	inline uint8_t opcodes0x47(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.hi, cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0x48(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.lo, cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0x49(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.lo, cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0x4a(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.lo, cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0x4b(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.lo, cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0x4c(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.lo, cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0x4d(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.lo, cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0x4e(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.lo, cpu.GetPrefixedHLAddress());
		return 7;
	};

	inline uint8_t opcodes0x4f(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_BC.lo, cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0x50(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.hi, cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0x51(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.hi, cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0x52(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.hi, cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0x53(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.hi, cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0x54(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.hi, cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0x55(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.hi, cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0x56(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.hi, cpu.GetPrefixedHLAddress());
		return 7;
	};

	inline uint8_t opcodes0x57(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.hi, cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0x58(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.lo, cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0x59(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.lo, cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0x5a(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.lo, cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0x5b(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.lo, cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0x5c(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.lo, cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0x5d(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.lo, cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0x5e(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.lo, cpu.GetPrefixedHLAddress());
		return 7;
	};

	inline uint8_t opcodes0x5f(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_DE.lo, cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0x60(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().hi, cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0x61(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().hi, cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0x62(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().hi, cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0x63(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().hi, cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0x64(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().hi, cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0x65(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().hi, cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0x66(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().hi, cpu.GetPrefixedHLAddress());
		return 7;
	};

	inline uint8_t opcodes0x67(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().hi, cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0x68(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().lo, cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0x69(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().lo, cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0x6a(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().lo, cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0x6b(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().lo, cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0x6c(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().lo, cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0x6d(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().lo, cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0x6e(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().lo, cpu.GetPrefixedHLAddress());
		return 7;
	};

	inline uint8_t opcodes0x6f(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHL().lo, cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0x70(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHLAddress(), cpu.m_reg_BC.hi);
		return 7;
	};

	inline uint8_t opcodes0x71(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHLAddress(), cpu.m_reg_BC.lo);
		return 7;
	};

	inline uint8_t opcodes0x72(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHLAddress(), cpu.m_reg_DE.hi);
		return 7;
	};

	inline uint8_t opcodes0x73(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHLAddress(), cpu.m_reg_DE.lo);
		return 7;
	};

	inline uint8_t opcodes0x74(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHLAddress(), cpu.GetPrefixedHL().hi);
		return 7;
	};

	inline uint8_t opcodes0x75(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHLAddress(), cpu.GetPrefixedHL().lo);
		return 7;
	};

	inline uint8_t opcodes0x76(Z80& cpu)
	{
		cpu.HALT();
		return 4;
	};

	inline uint8_t opcodes0x77(Z80& cpu)
	{
		cpu.LD(cpu.GetPrefixedHLAddress(), cpu.m_reg_AF.hi);
		return 7;
	};

	inline uint8_t opcodes0x78(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_AF.hi, cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0x79(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_AF.hi, cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0x7a(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_AF.hi, cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0x7b(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_AF.hi, cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0x7c(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_AF.hi, cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0x7d(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_AF.hi, cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0x7e(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_AF.hi, cpu.GetPrefixedHLAddress());
		return 7;
	};

	inline uint8_t opcodes0x7f(Z80& cpu)
	{
		cpu.LD(cpu.m_reg_AF.hi, cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0x80(Z80& cpu)
	{
		cpu.ADD(cpu.m_reg_AF.hi, cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0x81(Z80& cpu)
	{
		cpu.ADD(cpu.m_reg_AF.hi, cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0x82(Z80& cpu)
	{
		cpu.ADD(cpu.m_reg_AF.hi, cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0x83(Z80& cpu)
	{
		cpu.ADD(cpu.m_reg_AF.hi, cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0x84(Z80& cpu)
	{
		cpu.ADD(cpu.m_reg_AF.hi, cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0x85(Z80& cpu)
	{
		cpu.ADD(cpu.m_reg_AF.hi, cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0x86(Z80& cpu)
	{
		cpu.ADD_HL(cpu.m_reg_AF.hi);
		return 7;
	};

	inline uint8_t opcodes0x87(Z80& cpu)
	{
		cpu.ADD(cpu.m_reg_AF.hi, cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0x88(Z80& cpu)
	{
		cpu.ADC(cpu.m_reg_AF.hi, cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0x89(Z80& cpu)
	{
		cpu.ADC(cpu.m_reg_AF.hi, cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0x8a(Z80& cpu)
	{
		cpu.ADC(cpu.m_reg_AF.hi, cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0x8b(Z80& cpu)
	{
		cpu.ADC(cpu.m_reg_AF.hi, cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0x8c(Z80& cpu)
	{
		cpu.ADC(cpu.m_reg_AF.hi, cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0x8d(Z80& cpu)
	{
		cpu.ADC(cpu.m_reg_AF.hi, cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0x8e(Z80& cpu)
	{
		cpu.ADC_HL(cpu.m_reg_AF.hi);
		return 7;
	};

	inline uint8_t opcodes0x8f(Z80& cpu)
	{
		cpu.ADC(cpu.m_reg_AF.hi, cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0x90(Z80& cpu)
	{
		cpu.SUB(cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0x91(Z80& cpu)
	{
		cpu.SUB(cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0x92(Z80& cpu)
	{
		cpu.SUB(cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0x93(Z80& cpu)
	{
		cpu.SUB(cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0x94(Z80& cpu)
	{
		cpu.SUB(cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0x95(Z80& cpu)
	{
		cpu.SUB(cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0x96(Z80& cpu)
	{
		cpu.SUB_HL(cpu.m_reg_AF.hi);
		return 7;
	};

	inline uint8_t opcodes0x97(Z80& cpu)
	{
		cpu.SUB(cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0x98(Z80& cpu)
	{
		cpu.SBC(cpu.m_reg_AF.hi, cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0x99(Z80& cpu)
	{
		cpu.SBC(cpu.m_reg_AF.hi, cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0x9a(Z80& cpu)
	{
		cpu.SBC(cpu.m_reg_AF.hi, cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0x9b(Z80& cpu)
	{
		cpu.SBC(cpu.m_reg_AF.hi, cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0x9c(Z80& cpu)
	{
		cpu.SBC(cpu.m_reg_AF.hi, cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0x9d(Z80& cpu)
	{
		cpu.SBC(cpu.m_reg_AF.hi, cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0x9e(Z80& cpu)
	{
		cpu.SBC_HL(cpu.m_reg_AF.hi);
		return 7;
	};

	inline uint8_t opcodes0x9f(Z80& cpu)
	{
		cpu.SBC(cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0xa0(Z80& cpu)
	{
		cpu.AND(cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0xa1(Z80& cpu)
	{
		cpu.AND(cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0xa2(Z80& cpu)
	{
		cpu.AND(cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0xa3(Z80& cpu)
	{
		cpu.AND(cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0xa4(Z80& cpu)
	{
		cpu.AND(cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0xa5(Z80& cpu)
	{
		cpu.AND(cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0xa6(Z80& cpu)
	{
		cpu.AND_HL();
		return 7;
	};

	inline uint8_t opcodes0xa7(Z80& cpu)
	{
		cpu.AND(cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0xa8(Z80& cpu)
	{
		cpu.XOR(cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0xa9(Z80& cpu)
	{
		cpu.XOR(cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0xaa(Z80& cpu)
	{
		cpu.XOR(cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0xab(Z80& cpu)
	{
		cpu.XOR(cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0xac(Z80& cpu)
	{
		cpu.XOR(cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0xad(Z80& cpu)
	{
		cpu.XOR(cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0xae(Z80& cpu)
	{
		cpu.XOR_HL();
		return 7;
	};

	inline uint8_t opcodes0xaf(Z80& cpu)
	{
		cpu.XOR(cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0xb0(Z80& cpu)
	{
		cpu.OR(cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0xb1(Z80& cpu)
	{
		cpu.OR(cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0xb2(Z80& cpu)
	{
		cpu.OR(cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0xb3(Z80& cpu)
	{
		cpu.OR(cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0xb4(Z80& cpu)
	{
		cpu.OR(cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0xb5(Z80& cpu)
	{
		cpu.OR(cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0xb6(Z80& cpu)
	{
		cpu.OR_HL();
		return 7;
	};

	inline uint8_t opcodes0xb7(Z80& cpu)
	{
		cpu.OR(cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0xb8(Z80& cpu)
	{
		cpu.CP(cpu.m_reg_BC.hi);
		return 4;
	};

	inline uint8_t opcodes0xb9(Z80& cpu)
	{
		cpu.CP(cpu.m_reg_BC.lo);
		return 4;
	};

	inline uint8_t opcodes0xba(Z80& cpu)
	{
		cpu.CP(cpu.m_reg_DE.hi);
		return 4;
	};

	inline uint8_t opcodes0xbb(Z80& cpu)
	{
		cpu.CP(cpu.m_reg_DE.lo);
		return 4;
	};

	inline uint8_t opcodes0xbc(Z80& cpu)
	{
		cpu.CP(cpu.GetPrefixedHL().hi);
		return 4;
	};

	inline uint8_t opcodes0xbd(Z80& cpu)
	{
		cpu.CP(cpu.GetPrefixedHL().lo);
		return 4;
	};

	inline uint8_t opcodes0xbe(Z80& cpu)
	{
		cpu.CP_HL();
		return 7;
	};

	inline uint8_t opcodes0xbf(Z80& cpu)
	{
		cpu.CP(cpu.m_reg_AF.hi);
		return 4;
	};

	inline uint8_t opcodes0xc0(Z80& cpu)
	{
		return 11 ? cpu.RET(!cpu.ReadFlag(FLAG::ZERO)) : 5;
	};

	inline uint8_t opcodes0xc1(Z80& cpu)
	{
		cpu.POP(cpu.m_reg_BC);
		return 10;
	};

	inline uint8_t opcodes0xc2(Z80& cpu)
	{
		cpu.JP(!cpu.ReadFlag(FLAG::ZERO));
		return 10;
	};

	inline uint8_t opcodes0xc3(Z80& cpu)
	{
		cpu.JP();
		return 10;
	};

	inline uint8_t opcodes0xc4(Z80& cpu)
	{
		return 17 ? cpu.CALL(!cpu.ReadFlag(FLAG::ZERO)) : 10;
	};

	inline uint8_t opcodes0xc5(Z80& cpu)
	{
		cpu.PUSH(cpu.m_reg_BC);
		return 11;
	};

	inline uint8_t opcodes0xc6(Z80& cpu)
	{
		cpu.ADD(cpu.m_reg_AF.hi, cpu.ReadByte());
		return 7;
	};

	inline uint8_t opcodes0xc7(Z80& cpu)
	{
		cpu.RST(0x00);
		return 11;
	};

	inline uint8_t opcodes0xc8(Z80& cpu)
	{
		return 6 ? cpu.RET(cpu.ReadFlag(FLAG::ZERO)) : 5;
	};

	inline uint8_t opcodes0xc9(Z80& cpu)
	{
		cpu.RET();
		return 10;
	};

	inline uint8_t opcodes0xca(Z80& cpu)
	{
		cpu.JP(cpu.ReadFlag(FLAG::ZERO));
		return 10;
	};

	inline uint8_t opcodes0xcb(Z80& cpu)
	{
		cpu.CB();
		return 0;
	};

	inline uint8_t opcodes0xcc(Z80& cpu)
	{
		return 17 ? cpu.CALL(cpu.ReadFlag(FLAG::ZERO)) : 10;
	};

	inline uint8_t opcodes0xcd(Z80& cpu)
	{
		cpu.CALL();
		return 17;
	};

	inline uint8_t opcodes0xce(Z80& cpu)
	{
		cpu.ADC(cpu.m_reg_AF.hi, cpu.ReadByte());
		return 7;
	};

	inline uint8_t opcodes0xcf(Z80& cpu)
	{
		cpu.RST(0x08);
		return 11;
	};

	inline uint8_t opcodes0xd0(Z80& cpu)
	{
		return 11 ? cpu.RET(!cpu.ReadFlag(FLAG::CARRY)) : 5;
	};

	inline uint8_t opcodes0xd1(Z80& cpu)
	{
		cpu.POP(cpu.m_reg_DE);
		return 10;
	};

	inline uint8_t opcodes0xd2(Z80& cpu)
	{
		cpu.JP(!cpu.ReadFlag(FLAG::CARRY));
		return 10;
	};

	inline uint8_t opcodes0xd3(Z80& cpu)
	{
		cpu.OUT_N(cpu.m_reg_AF.hi);
		return 11;
	};

	inline uint8_t opcodes0xd4(Z80& cpu)
	{
		return 17 ? cpu.CALL(!cpu.ReadFlag(FLAG::CARRY)) : 10;
	};

	inline uint8_t opcodes0xd5(Z80& cpu)
	{
		cpu.PUSH(cpu.m_reg_DE);
		return 11;
	};

	inline uint8_t opcodes0xd6(Z80& cpu)
	{
		cpu.SUB(cpu.ReadByte());
		return 7;
	};

	inline uint8_t opcodes0xd7(Z80& cpu)
	{
		cpu.RST(0x10);
		return 11;
	};

	inline uint8_t opcodes0xd8(Z80& cpu)
	{
		return 6 ? cpu.RET(cpu.ReadFlag(FLAG::CARRY)) : 5;
	};

	inline uint8_t opcodes0xd9(Z80& cpu)
	{
		cpu.EXX();
		return 4;
	};

	inline uint8_t opcodes0xda(Z80& cpu)
	{
		cpu.JP(cpu.ReadFlag(FLAG::CARRY));
		return 10;
	};

	inline uint8_t opcodes0xdb(Z80& cpu)
	{
		cpu.IN_N(cpu.m_reg_AF.hi);
		return 11;
	};

	inline uint8_t opcodes0xdc(Z80& cpu)
	{
		return 17 ? cpu.CALL(cpu.ReadFlag(FLAG::CARRY)) : 10;
	};

	inline uint8_t opcodes0xdd(Z80& cpu)
	{
		cpu.DD();
		return 0;
	};

	inline uint8_t opcodes0xde(Z80& cpu)
	{
		cpu.SBC(cpu.m_reg_AF.hi, cpu.ReadByte());
		return 7;
	};

	inline uint8_t opcodes0xdf(Z80& cpu)
	{
		cpu.RST(0x18);
		return 11;
	};

	inline uint8_t opcodes0xe0(Z80& cpu)
	{
		return 11 ? cpu.RET(!cpu.ReadFlag(FLAG::PARITY_OVERFLOW)) : 5;
	};

	inline uint8_t opcodes0xe1(Z80& cpu)
	{
		cpu.POP(cpu.GetPrefixedHL());
		return 10;
	};

	inline uint8_t opcodes0xe2(Z80& cpu)
	{
		cpu.JP(!cpu.ReadFlag(FLAG::PARITY_OVERFLOW));
		return 10;
	};

	inline uint8_t opcodes0xe3(Z80& cpu)
	{
		cpu.EX_SPHL();
		return 19;
	};

	inline uint8_t opcodes0xe4(Z80& cpu)
	{
		return 17 ? cpu.CALL(!cpu.ReadFlag(FLAG::PARITY_OVERFLOW)) : 10;
	};

	inline uint8_t opcodes0xe5(Z80& cpu)
	{
		cpu.PUSH(cpu.GetPrefixedHL());
		return 11;
	};

	inline uint8_t opcodes0xe6(Z80& cpu)
	{
		cpu.AND(cpu.ReadByte());
		return 7;
	};

	inline uint8_t opcodes0xe7(Z80& cpu)
	{
		cpu.RST(0x20);
		return 11;
	};

	inline uint8_t opcodes0xe8(Z80& cpu)
	{
		return 6 ? cpu.RET(cpu.ReadFlag(FLAG::PARITY_OVERFLOW)) : 5;
	};

	inline uint8_t opcodes0xe9(Z80& cpu)
	{
		cpu.JP(cpu.GetPrefixedHLAddress());
		return 4;
	};

	inline uint8_t opcodes0xea(Z80& cpu)
	{
		cpu.JP(cpu.ReadFlag(FLAG::PARITY_OVERFLOW));
		return 10;
	};

	inline uint8_t opcodes0xeb(Z80& cpu)
	{
		cpu.EX(cpu.m_reg_DE, cpu.GetPrefixedHL());
		return 4;
	};

	inline uint8_t opcodes0xec(Z80& cpu)
	{
		return 17 ? cpu.CALL(cpu.ReadFlag(FLAG::PARITY_OVERFLOW)) : 10;
	};

	inline uint8_t opcodes0xed(Z80& cpu)
	{
		cpu.ED();
		return 0;
	};

	inline uint8_t opcodes0xee(Z80& cpu)
	{
		cpu.XOR(cpu.ReadByte());
		return 7;
	};

	inline uint8_t opcodes0xef(Z80& cpu)
	{
		cpu.RST(0x28);
		return 11;
	};

	inline uint8_t opcodes0xf0(Z80& cpu)
	{
		return 11 ? cpu.RET(!cpu.ReadFlag(FLAG::SIGN)) : 5;
	};

	inline uint8_t opcodes0xf1(Z80& cpu)
	{
		cpu.POP(cpu.m_reg_AF);
		return 10;
	};

	inline uint8_t opcodes0xf2(Z80& cpu)
	{
		cpu.JP(!cpu.ReadFlag(FLAG::SIGN));
		return 10;
	};

	inline uint8_t opcodes0xf3(Z80& cpu)
	{
		cpu.DI();
		return 4;
	};

	inline uint8_t opcodes0xf4(Z80& cpu)
	{
		return 17 ? cpu.CALL(!cpu.ReadFlag(FLAG::SIGN)) : 10;
	};

	inline uint8_t opcodes0xf5(Z80& cpu)
	{
		cpu.PUSH(cpu.m_reg_AF);
		return 11;
	};

	inline uint8_t opcodes0xf6(Z80& cpu)
	{
		cpu.OR(cpu.ReadByte());
		return 7;
	};

	inline uint8_t opcodes0xf7(Z80& cpu)
	{
		cpu.RST(0x30);
		return 11;
	};

	inline uint8_t opcodes0xf8(Z80& cpu)
	{
		return 6 ? cpu.RET(cpu.ReadFlag(FLAG::SIGN)) : 5;
	};

	inline uint8_t opcodes0xf9(Z80& cpu)
	{
		cpu.LD_SP_HL();
		return 6;
	};

	inline uint8_t opcodes0xfa(Z80& cpu)
	{
		cpu.JP(cpu.ReadFlag(FLAG::SIGN));
		return 10;
	};

	inline uint8_t opcodes0xfb(Z80& cpu)
	{
		cpu.EI();
		return 4;
	};

	inline uint8_t opcodes0xfc(Z80& cpu)
	{
		return 17 ? cpu.CALL(cpu.ReadFlag(FLAG::SIGN)) : 10;
	};

	inline uint8_t opcodes0xfd(Z80& cpu)
	{
		cpu.FD();
		return 0;
	};

	inline uint8_t opcodes0xfe(Z80& cpu)
	{
		cpu.CP(cpu.ReadByte());
		return 7;
	};

	inline uint8_t opcodes0xff(Z80& cpu)
	{
		cpu.RST(0x38);
		return 11;
	};

	inline uint8_t UnexpectedOPCode(Z80& cpu)
	{
		cpu.UNUSED();
		return 0;
	}

	OPCodeFunc s_opcode_funcs [256] = 
	{
		&opcodes0x00,
		&opcodes0x01,
		&opcodes0x02,
		&opcodes0x03,
		&opcodes0x04,
		&opcodes0x05,
		&opcodes0x06,
		&opcodes0x07,
		&opcodes0x08,
		&opcodes0x09,
		&opcodes0x0a,
		&opcodes0x0b,
		&opcodes0x0c,
		&opcodes0x0d,
		&opcodes0x0e,
		&opcodes0x0f,
		&opcodes0x10,
		&opcodes0x11,
		&opcodes0x12,
		&opcodes0x13,
		&opcodes0x14,
		&opcodes0x15,
		&opcodes0x16,
		&opcodes0x17,
		&opcodes0x18,
		&opcodes0x19,
		&opcodes0x1a,
		&opcodes0x1b,
		&opcodes0x1c,
		&opcodes0x1d,
		&opcodes0x1e,
		&opcodes0x1f,
		&opcodes0x20,
		&opcodes0x21,
		&opcodes0x22,
		&opcodes0x23,
		&opcodes0x24,
		&opcodes0x25,
		&opcodes0x26,
		&opcodes0x27,
		&opcodes0x28,
		&opcodes0x29,
		&opcodes0x2a,
		&opcodes0x2b,
		&opcodes0x2c,
		&opcodes0x2d,
		&opcodes0x2e,
		&opcodes0x2f,
		&opcodes0x30,
		&opcodes0x31,
		&opcodes0x32,
		&opcodes0x33,
		&opcodes0x34,
		&opcodes0x35,
		&opcodes0x36,
		&opcodes0x37,
		&opcodes0x38,
		&opcodes0x39,
		&opcodes0x3a,
		&opcodes0x3b,
		&opcodes0x3c,
		&opcodes0x3d,
		&opcodes0x3e,
		&opcodes0x3f,
		&opcodes0x40,
		&opcodes0x41,
		&opcodes0x42,
		&opcodes0x43,
		&opcodes0x44,
		&opcodes0x45,
		&opcodes0x46,
		&opcodes0x47,
		&opcodes0x48,
		&opcodes0x49,
		&opcodes0x4a,
		&opcodes0x4b,
		&opcodes0x4c,
		&opcodes0x4d,
		&opcodes0x4e,
		&opcodes0x4f,
		&opcodes0x50,
		&opcodes0x51,
		&opcodes0x52,
		&opcodes0x53,
		&opcodes0x54,
		&opcodes0x55,
		&opcodes0x56,
		&opcodes0x57,
		&opcodes0x58,
		&opcodes0x59,
		&opcodes0x5a,
		&opcodes0x5b,
		&opcodes0x5c,
		&opcodes0x5d,
		&opcodes0x5e,
		&opcodes0x5f,
		&opcodes0x60,
		&opcodes0x61,
		&opcodes0x62,
		&opcodes0x63,
		&opcodes0x64,
		&opcodes0x65,
		&opcodes0x66,
		&opcodes0x67,
		&opcodes0x68,
		&opcodes0x69,
		&opcodes0x6a,
		&opcodes0x6b,
		&opcodes0x6c,
		&opcodes0x6d,
		&opcodes0x6e,
		&opcodes0x6f,
		&opcodes0x70,
		&opcodes0x71,
		&opcodes0x72,
		&opcodes0x73,
		&opcodes0x74,
		&opcodes0x75,
		&opcodes0x76,
		&opcodes0x77,
		&opcodes0x78,
		&opcodes0x79,
		&opcodes0x7a,
		&opcodes0x7b,
		&opcodes0x7c,
		&opcodes0x7d,
		&opcodes0x7e,
		&opcodes0x7f,
		&opcodes0x80,
		&opcodes0x81,
		&opcodes0x82,
		&opcodes0x83,
		&opcodes0x84,
		&opcodes0x85,
		&opcodes0x86,
		&opcodes0x87,
		&opcodes0x88,
		&opcodes0x89,
		&opcodes0x8a,
		&opcodes0x8b,
		&opcodes0x8c,
		&opcodes0x8d,
		&opcodes0x8e,
		&opcodes0x8f,
		&opcodes0x90,
		&opcodes0x91,
		&opcodes0x92,
		&opcodes0x93,
		&opcodes0x94,
		&opcodes0x95,
		&opcodes0x96,
		&opcodes0x97,
		&opcodes0x98,
		&opcodes0x99,
		&opcodes0x9a,
		&opcodes0x9b,
		&opcodes0x9c,
		&opcodes0x9d,
		&opcodes0x9e,
		&opcodes0x9f,
		&opcodes0xa0,
		&opcodes0xa1,
		&opcodes0xa2,
		&opcodes0xa3,
		&opcodes0xa4,
		&opcodes0xa5,
		&opcodes0xa6,
		&opcodes0xa7,
		&opcodes0xa8,
		&opcodes0xa9,
		&opcodes0xaa,
		&opcodes0xab,
		&opcodes0xac,
		&opcodes0xad,
		&opcodes0xae,
		&opcodes0xaf,
		&opcodes0xb0,
		&opcodes0xb1,
		&opcodes0xb2,
		&opcodes0xb3,
		&opcodes0xb4,
		&opcodes0xb5,
		&opcodes0xb6,
		&opcodes0xb7,
		&opcodes0xb8,
		&opcodes0xb9,
		&opcodes0xba,
		&opcodes0xbb,
		&opcodes0xbc,
		&opcodes0xbd,
		&opcodes0xbe,
		&opcodes0xbf,
		&opcodes0xc0,
		&opcodes0xc1,
		&opcodes0xc2,
		&opcodes0xc3,
		&opcodes0xc4,
		&opcodes0xc5,
		&opcodes0xc6,
		&opcodes0xc7,
		&opcodes0xc8,
		&opcodes0xc9,
		&opcodes0xca,
		&opcodes0xcb,
		&opcodes0xcc,
		&opcodes0xcd,
		&opcodes0xce,
		&opcodes0xcf,
		&opcodes0xd0,
		&opcodes0xd1,
		&opcodes0xd2,
		&opcodes0xd3,
		&opcodes0xd4,
		&opcodes0xd5,
		&opcodes0xd6,
		&opcodes0xd7,
		&opcodes0xd8,
		&opcodes0xd9,
		&opcodes0xda,
		&opcodes0xdb,
		&opcodes0xdc,
		&opcodes0xdd,
		&opcodes0xde,
		&opcodes0xdf,
		&opcodes0xe0,
		&opcodes0xe1,
		&opcodes0xe2,
		&opcodes0xe3,
		&opcodes0xe4,
		&opcodes0xe5,
		&opcodes0xe6,
		&opcodes0xe7,
		&opcodes0xe8,
		&opcodes0xe9,
		&opcodes0xea,
		&opcodes0xeb,
		&opcodes0xec,
		&opcodes0xed,
		&opcodes0xee,
		&opcodes0xef,
		&opcodes0xf0,
		&opcodes0xf1,
		&opcodes0xf2,
		&opcodes0xf3,
		&opcodes0xf4,
		&opcodes0xf5,
		&opcodes0xf6,
		&opcodes0xf7,
		&opcodes0xf8,
		&opcodes0xf9,
		&opcodes0xfa,
		&opcodes0xfb,
		&opcodes0xfc,
		&opcodes0xfd,
		&opcodes0xfe,
		&opcodes0xff
	};
}
